services:
  # api-gateway will use port 8080
  apigateway:
    build: apigateway
    hostname: apigateway
    container_name: apigateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - customer-service
      - asset-service
      - staff-service
      - incident-service

  incident-service:
    build: incident-service
    hostname: incident-service
    container_name: incident-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongodb-incident:
        condition: service_healthy

  mongodb-incident:
    image: mongo:6.0
    hostname: mongodb-incident
    container_name: mongodb-incident
    volumes:
      - ./data/mongodb-incident:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 10

  mongo-express-incident:
    image: mongo-express:1.0.2
    container_name: mongo-express-incident
    hostname: mongo-express-incident
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb-incident
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH=false
    depends_on:
      mongodb-incident:
        condition: service_healthy



  customer-service:
    build: customer-service
    hostname: customer-service
    container_name: customer-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql1:
        condition: service_healthy

  mysql1:
    image: mysql:8.0
    hostname: mysql1
    container_name: mysql1-customer
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=customer-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    volumes:
      - ./data/mysql1:/var/lib/mysql1
      - ./data/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-uuser",
          "-ppwd",
          "-h",
          "localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin1:
    image: phpmyadmin:5.2.0
    container_name: phpmyadmin1-customer
    hostname: phpmyadmin1
    links:
      - mysql1
    restart: always
    environment:
      - PMA_ARBITRARY=1







  staff-service:
    build: staff-service
    hostname: staff-service
    container_name: staff-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql2:
        condition: service_healthy

  mysql2:
    image: mysql:8.0
    hostname: mysql2
    container_name: mysql2-staff
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=staff-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    volumes:
      - ./data/mysql2:/var/lib/mysql2
      - ./data/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-uuser",
          "-ppwd",
          "-h",
          "localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin2:
    image: phpmyadmin:5.2.0
    container_name: phpmyadmin2-staff
    hostname: phpmyadmin2
    links:
      - mysql2
    restart: always
    environment:
      - PMA_ARBITRARY=1




  asset-service:
    build: asset-service
    hostname: asset-service
    container_name: asset-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgres1:
        condition: service_healthy

  postgres1:
    image: postgres:latest              #as of April 7, 2025, latest version is PostgreSQL 17.4
    container_name: postgres1-asset
    hostname: postgres1
    environment:
      - POSTGRES_USER=user
      - PGUSER=user                     #need this to avoid fatal error no role ROOT found
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=asset-db      #must match what's in the application.yml url
    healthcheck:
      test: "pg_isready -h postgres1"
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-asset
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@ionascu.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres1
