server:
  port: 7004
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.itservice: DEBUG

spring:
  application:
    name: incident-service
  config:
    activate:
      on-profile: default
  data:
    mongodb:
      host: localhost
      port: 27017
      database: incident-db

microservices:
  customer-service:
    base-url: http://localhost:7001
  staff-service:
    base-url: http://localhost:7002
  asset-service:
    base-url: http://localhost:7003

---
server:
  port: 8080

spring:
  application:
    name: incident-service
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb-incident
      port: 27017
      database: incident-db

microservices:
  customer-service:
    base-url: http://customer-service:8080
  staff-service:
    base-url: http://staff-service:8080
  asset-service:
    base-url: http://asset-service:8080

---
spring:
  config:
    activate:
      on-profile: testing-profile
  data:
    mongodb:
      database: incident-db-test

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 7.0.5

microservices:
  customer-service:
    base-url: http://localhost:7001
  staff-service:
    base-url: http://localhost:7002
  asset-service:
    base-url: http://localhost:7003
